//@ts-check
import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "node:fs";
import path from "node:path";

const prod = process.argv[2] === "production";

const pad2 = (v) => String(v).padStart(2, "0");
const formatBuildTime = (d) => {
    const offsetMin = -d.getTimezoneOffset();
    const sign = offsetMin >= 0 ? "+" : "-";
    const abs = Math.abs(offsetMin);
    return `${d.getFullYear()}-${pad2(d.getMonth() + 1)}-${pad2(d.getDate())}T${pad2(d.getHours())}:${pad2(d.getMinutes())} (UTC${sign}${pad2(Math.floor(abs / 60))}:${pad2(abs % 60)})`;
};
const buildTime = formatBuildTime(new Date());

const manifestJson = JSON.parse(fs.readFileSync("./manifest.json") + "");
const packageJson = JSON.parse(fs.readFileSync("./package.json") + "");

const vaultPath = process.env.OBSIDIAN_VAULT_PATH ?? "C:\\Obsidian\\Dev";
const outDir = path.join(vaultPath, ".obsidian", "plugins", "obsidian-couchsync");

if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
}

const copyStaticFiles = {
    name: "copy-static-files",
    setup(build) {
        build.onEnd(() => {
            try {
                fs.copyFileSync("manifest.json", path.join(outDir, "manifest.json"));
                if (fs.existsSync("styles.css")) {
                    fs.copyFileSync("styles.css", path.join(outDir, "styles.css"));
                }
                console.log("Built to " + outDir);
            } catch (e) {
                console.error("Failed to copy static files:", e);
            }
        });
    },
};

const context = await esbuild.context({
    banner: {
        js: `/* CouchSync - generated by esbuild */`,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    define: {
        MANIFEST_VERSION: `"${manifestJson.version}"`,
        PACKAGE_VERSION: `"${packageJson.version}"`,
        __BUILD_TIME__: JSON.stringify(buildTime),
        global: "window",
    },
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        // Note: NOT including builtins — 'events' polyfill etc. must be bundled for mobile
    ],
    format: "cjs",
    target: "es2022",
    logLevel: "info",
    platform: "browser",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: path.join(outDir, "main.js"),
    minify: prod,
    plugins: [copyStaticFiles],
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
