//@ts-check

import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import sveltePlugin from "esbuild-svelte";
import { sveltePreprocess } from "svelte-preprocess";
import fs from "node:fs";
import inlineWorkerPlugin from "esbuild-plugin-inline-worker";
import path from "node:path";

const prod = process.argv[2] === "production" || process.env?.BUILD_MODE === "production";
const keepTest = true; //!prod;

const manifestJson = JSON.parse(fs.readFileSync("./manifest.json") + "");
const packageJson = JSON.parse(fs.readFileSync("./package.json") + "");
const updateInfo = JSON.stringify(fs.readFileSync("./updates.md") + "");

const vaultPath = process.env.OBSIDIAN_VAULT_PATH ?? "C:\\Obsidian\\Dev";
const outDir = path.join(
    vaultPath,
    ".obsidian",
    "plugins",
    "obsidian-couchsync"
);

if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
}

const moduleAliasPlugin = {
    name: "module-alias",
    setup(build) {
        build.onResolve({ filter: /.(dev)(.ts|)$/ }, (args) => {
            if (prod) {
                let prodTs = args.path.replace(".dev", ".prod");
                const statFile = prodTs.endsWith(".ts") ? prodTs : prodTs + ".ts";
                const realPath = path.join(args.resolveDir, statFile);
                console.log(`Checking ${statFile}`);
                if (fs.existsSync(realPath)) {
                    console.log(`Replaced ${args.path} with ${prodTs}`);
                    return {
                        path: realPath,
                        namespace: "file",
                    };
                }
            }
            return null;
        });
        build.onResolve({ filter: /.(platform)(.ts|)$/ }, (args) => {
            if (prod) {
                let prodTs = args.path.replace(".platform", ".obsidian");
                const statFile = prodTs.endsWith(".ts") ? prodTs : prodTs + ".ts";
                const realPath = path.join(args.resolveDir, statFile);
                console.log(`Checking ${statFile}`);
                if (fs.existsSync(realPath)) {
                    console.log(`Replaced ${args.path} with ${prodTs}`);
                    return {
                        path: realPath,
                        namespace: "file",
                    };
                }
            }
            return null;
        });
    },
};

const copyStaticFiles = {
    name: "copy-static-files",
    setup(build) {
        build.onEnd(() => {
            try {
                fs.copyFileSync("manifest.json", path.join(outDir, "manifest.json"));

                if (fs.existsSync("styles.css")) {
                    fs.copyFileSync("styles.css", path.join(outDir, "styles.css"));
                }

                console.log("Built to " + outDir);
            } catch (e) {
                console.error("Failed to copy static files:", e);
            }
        });
    },
};

const externals = [
    "obsidian",
    "electron",
    "crypto",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
];

const context = await esbuild.context({
    banner: {
        js: `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    define: {
        MANIFEST_VERSION: `"${manifestJson.version}"`,
        PACKAGE_VERSION: `"${packageJson.version}"`,
        UPDATE_INFO: `${updateInfo}`,
        global: "window",
    },
    external: externals,
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    platform: "browser",
    metafile: true,
    sourcemap: prod ? false : "inline",
    treeShaking: prod,
    outfile: path.join(outDir, "main.js"),
    mainFields: ["browser", "module", "main"],
    minify: prod,
    dropLabels: prod && !keepTest ? ["TEST", "DEV"] : [],
    plugins: [
        moduleAliasPlugin,
        inlineWorkerPlugin({
            external: externals,
            treeShaking: true,
        }),
        sveltePlugin({
            preprocess: sveltePreprocess(),
            compilerOptions: { css: "injected", preserveComments: false },
        }),
        copyStaticFiles,
    ],
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
