//@ts-check
import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "node:fs";
import path from "node:path";

const prod = process.argv[2] === "production";

const manifestJson = JSON.parse(fs.readFileSync("./manifest.json") + "");
const packageJson = JSON.parse(fs.readFileSync("./package.json") + "");

const vaultPath = process.env.OBSIDIAN_VAULT_PATH ?? "C:\\Obsidian\\Dev";
const outDir = path.join(vaultPath, ".obsidian", "plugins", "obsidian-couchsync");

if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
}

const copyStaticFiles = {
    name: "copy-static-files",
    setup(build) {
        build.onEnd(() => {
            try {
                fs.copyFileSync("manifest.json", path.join(outDir, "manifest.json"));
                if (fs.existsSync("styles.css")) {
                    fs.copyFileSync("styles.css", path.join(outDir, "styles.css"));
                }
                console.log("Built to " + outDir);
            } catch (e) {
                console.error("Failed to copy static files:", e);
            }
        });
    },
};

const context = await esbuild.context({
    banner: {
        js: `/* CouchSync - generated by esbuild */`,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    define: {
        MANIFEST_VERSION: `"${manifestJson.version}"`,
        PACKAGE_VERSION: `"${packageJson.version}"`,
        global: "window",
    },
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins,
    ],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    platform: "browser",
    sourcemap: prod ? false : "inline",
    treeShaking: prod,
    outfile: path.join(outDir, "main.js"),
    mainFields: ["main", "browser"],
    minify: prod,
    plugins: [copyStaticFiles],
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
